#!/bin/bash

if [ -f ~/.ssh/.redmine ]; then
  source ~/.ssh/.redmine
fi

if [ -f .redmine ]; then
  source .redmine
fi


if [ "$#" -gt 0 ]; then
  PAGE_NAME=$1

  curl -s -3 \
  "https://$SERVER/projects/$PROJECT/wiki/$PAGE_NAME.xml?key=$KEY" 
fi

